/**
 * Pure, DOM-free helpers shared by the content script, the service worker, and the tests.
 *
 * The whole extension is built around one idea: given the user's chosen country override and their
 * pinned interface language, compute the exact set of Google search-URL query parameters that must
 * be present (or absent), then apply that set to whatever URL we're looking at. Keeping this logic
 * here — with no `chrome.*`, `document`, or `location` access — is what lets the same rules drive
 * the network-layer rewrite (declarativeNetRequest), the content-script fallback, and unit tests.
 */

/** A country override: an ISO 3166-1 alpha-2 code plus whether to hard-restrict results (`cr`). */
export interface Override {
  code: string;
  strict: boolean;
}

/** The full persisted state (see `chrome.storage.sync`). `override: null` means "Auto". */
export interface State {
  override: Override | null;
  favourites: string[];
  lang: string;
}

/**
 * A desired query-parameter map: `value` → force `key=value`; `null` → ensure `key` is absent.
 * Only the parameters we own (`gl`, `cr`, `hl`) ever appear here, so everything else is untouched.
 */
export type ParamSpec = Record<string, string | null>;

import GOOGLE_DOMAINS_JSON from "./google-domains.json";

/**
 * Google domains we operate on — the single source of truth shared with the manifest's
 * `matches`/`host_permissions` (generated by the build) and the DNR rule's `requestDomains`
 * (which matches these and their subdomains).
 */
export const GOOGLE_DOMAINS: readonly string[] = GOOGLE_DOMAINS_JSON;

/**
 * Content-script `matches` / `host_permissions` patterns for the search results page. Match patterns
 * cannot wildcard the TLD (`*.google.*` is invalid), so we enumerate the domains above. Google has
 * served localised results from `google.com` since 2017, so `google.com` is the primary target and
 * the ccTLDs are a convenience for users who still land on them.
 */
export const SEARCH_MATCH_PATTERNS = GOOGLE_DOMAINS.map((d) => `*://*.${d}/search*`);
export const HOST_PERMISSION_PATTERNS = GOOGLE_DOMAINS.map((d) => `*://*.${d}/*`);

/**
 * Default state used before anything is stored, and to fill partial reads. `lang` starts empty
 * ("undetected") rather than "en" so the content script detects the user's real interface language
 * on first run — pinning "en" for a non-English user would itself change their language.
 */
export function defaultState(): State {
  return { override: null, favourites: [], lang: "" };
}

/** Reduce an arbitrary language tag to Google's primary subtag, lower-cased (`en-GB` → `en`). */
export function primarySubtag(tag: string): string {
  return tag.split("-")[0]!.toLowerCase();
}

/**
 * The parameters to enforce for a given override + pinned language.
 *
 * - Override set: pin `gl` (country bias) and `hl` (interface language, so switching country never
 *   changes the language); add `cr` only when strict, otherwise remove any stale `cr`. `hl` is
 *   pinned only when the language is known — an empty `lang` leaves `hl` untouched rather than
 *   emitting `hl=` (which Google treats as absent and re-derives from `gl`, the very thing we guard
 *   against). In practice callers always resolve the language before setting an override.
 * - Override null ("Auto"): remove all three of our params so Google reverts to its own defaults.
 */
export function desiredParams(override: Override | null, lang: string): ParamSpec {
  if (!override) return { gl: null, cr: null, hl: null };
  const params: ParamSpec = {
    gl: override.code.toLowerCase(),
    cr: override.strict ? `country${override.code.toUpperCase()}` : null,
  };
  if (lang) params.hl = lang;
  return params;
}

/**
 * True when `url` does not already satisfy `params`. Compares parameter-by-parameter (not by full
 * string) so cosmetic re-encoding of unrelated params never triggers a needless reload/redirect.
 */
export function needsUpdate(url: string, params: ParamSpec): boolean {
  const sp = new URL(url).searchParams;
  for (const [key, value] of Object.entries(params)) {
    const current = sp.get(key);
    if (value === null ? current !== null : current !== value) return true;
  }
  return false;
}

/** Apply `params` to `url` (set non-null keys, delete null keys) and return the resulting URL. */
export function applyToUrl(url: string, params: ParamSpec): string {
  const u = new URL(url);
  for (const [key, value] of Object.entries(params)) {
    if (value === null) u.searchParams.delete(key);
    else u.searchParams.set(key, value);
  }
  return u.toString();
}

/**
 * Determine the interface language to pin, in priority order:
 *   1. an explicit `hl` already on the URL (trust it verbatim — it's a valid Google hl),
 *   2. the results page's `<html lang>` (primary subtag),
 *   3. the browser UI language (primary subtag),
 *   4. `en` as a last resort.
 */
export function detectLang(
  url: string,
  htmlLang?: string | null,
  navLang?: string | null,
): string {
  const hl = new URL(url).searchParams.get("hl");
  if (hl) return hl;
  if (htmlLang) return primarySubtag(htmlLang);
  if (navLang) return primarySubtag(navLang);
  return "en";
}
